/* Additive screens for the existing journal interface. No credentials are embedded. */
(function(){
  'use strict';
  const E=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const date=v=>v?new Date(v).toLocaleString('th-TH'):'—';
  const field=(name,label,type='text',value='',required=true)=>`<label>${E(label)}<input name="${E(name)}" type="${type}" value="${E(value)}" ${required?'required':''}></label>`;
  const text=(name,label,value='',required=false)=>`<label>${E(label)}<textarea name="${name}" ${required?'required':''}>${E(value)}</textarea></label>`;
  const select=(name,label,options,value='')=>`<label>${E(label)}<select name="${name}">${options.map(o=>`<option value="${E(o[0])}" ${String(o[0])===String(value)?'selected':''}>${E(o[1])}</option>`).join('')}</select></label>`;
  const btn=(action,label,id='')=>`<button type="button" data-j-action="${action}" data-id="${E(id)}">${E(label)}</button>`;
  const form=(action,body,label='บันทึก')=>`<form class="panel" data-j-form="${action}">${body}<button type="submit">${label}</button></form>`;
  const rec=[['ACCEPT','Accept — ตอบรับ'],['MINOR','Minor Revision — แก้ไขเล็กน้อย'],['MAJOR','Major Revision — แก้ไขสาระสำคัญ'],['REJECT','Reject — ไม่รับพิจารณา']];
  let root,mode='',context=null,reviewerToken=sessionStorage.getItem('stjReviewerToken')||'';
  const author=()=>sessionStorage.getItem('stjAuthorToken')||'';
  const editor=()=>sessionStorage.getItem('stjToken')||author();
  const api=(method,payload={},role='EDITOR')=>stjApi(method,{...payload,token:role==='REVIEWER'?reviewerToken:role==='AUTHOR'?author():editor()});
  function message(text,error=false){const n=document.getElementById('journalMessage');if(n){n.textContent=text;n.className=error?'error':'journal-success';}}
  function display(html){root.innerHTML=`<div id="journalMessage" role="status" aria-live="polite"></div>${html}`;}
  function title(t){return `<h1 class="journal-heading">${E(t)}</h1>`;}
  async function download(id,role='EDITOR'){const f=await api('getAuthorizedFile',{fileId:id},role),binary=atob(f.base64),bytes=Uint8Array.from(binary,c=>c.charCodeAt(0)),url=URL.createObjectURL(new Blob([bytes],{type:f.mime})),a=document.createElement('a');a.href=url;a.download=f.name;a.click();setTimeout(()=>URL.revokeObjectURL(url),10000);}
  const fileButtons=(files,role)=>`<div class="journal-files">${files.map(f=>btn('file-'+role,`${f.name} · v${f.version}`,f.fileId)).join('')}</div>`;
  async function open(which,id){
    mode=which;context=null;
    if(document.getElementById('journalPanel')){document.querySelectorAll('.view').forEach(n=>n.classList.remove('active'));document.getElementById('journalPanel').classList.add('active');document.querySelector('#journalPanel nav').hidden=which==='author';document.getElementById('detail')?.classList.add('hidden');history.replaceState(null,'','#journal');scrollTo(0,0);}
    display(title('กำลังโหลด…'));
    try{
      if(which==='setup'){display(title('เตรียมระบบวารสาร')+`<div class="panel"><p>สำรองฐานข้อมูลและไฟล์ทั้งหมด จำกัดการแชร์ด้วยลิงก์ และเพิ่มตารางโดยไม่ลบข้อมูลเดิม</p><p>ต้นฉบับจะดาวน์โหลดผ่านระบบที่ตรวจสิทธิ์ ส่วน Template ดาวน์โหลดจาก GitHub ได้ตามเดิม</p>${btn('initialize','สำรองข้อมูลและเตรียมระบบ')}</div>`);return;}
      if(which==='overview'){const d=await api('getJournalOverview');context=d;display(overview(d));return;}
      if(which==='reviewers'){
        const rows=await api('listReviewers');context=rows;
        display(title('ผู้ทรงคุณวุฒิ')+form('reviewer-search',field('query','ค้นหาชื่อ / สังกัด','text','',false)+field('expertise','ความเชี่ยวชาญ','text','',false),'ค้นหา')+reviewerList(rows)+btn('new-reviewer','เพิ่มผู้ทรงคุณวุฒิ'));return;
      }
      if(which==='reviewer-edit'){const r=(id&&context?.find?.(x=>x.reviewer_id===id))||{};display(reviewerForm(r));return;}
      if(which==='manuscript'){
        if(!id){display(title('การประเมินและการตัดสิน')+form('open-manuscript',field('manuscriptId','รหัสบทความ'),'เปิดบทความ'));return;}
        const d=await api('getDecisionContext',{manuscriptId:id});context=d;
        const assignments=d.assignments.map((a,i)=>`<div class="result"><h3>ผู้ประเมิน ${i+1}: ${E(a.reviewerName)}</h3><p>รอบ ${a.round} · ${E(a.invitation_status)} · ${E(a.review_status)}</p><p>เชิญ ${date(a.assigned_at)} · ครบกำหนด ${date(a.due_at)} · ส่งผล ${date(a.completed_at)}</p>${a.result?`<p><b>${E(a.result.recommendation)}</b> · คะแนน ${E(a.result.scores_json)}</p><p>จุดเด่น: ${E(a.result.strengths)}</p><p>ข้อเสนอแนะ: ${E(a.result.suggestions)}</p><p>ถึงผู้เขียน: ${E(a.result.comment_to_author)}</p><details><summary>Confidential Comment — เฉพาะกองบรรณาธิการ</summary><p>${E(a.result.confidential_comment)}</p></details>`:!a.cancelled_at?btn('cancel-assignment','ยกเลิกงานนี้',a.assignment_id):'<p>ยกเลิกแล้ว</p>'}</div>`).join('');
        display(title(d.submission.title_th)+`<p>${E(id)} · ${E(d.submission.status)} · v${d.meta.current_version}</p><h2>การประเมินโดยผู้ทรงคุณวุฒิ</h2><p class="tag">${E(d.progress)} Reviews Complete ${d.complete?'— ผลประเมินครบแล้ว':''}</p>${assignments}${btn('assign','+ มอบหมายผู้ทรงคุณวุฒิ',id)} ${d.complete||d.submission.status==='REVISED'?btn('decision','พิจารณาผลการประเมิน',id):'<button disabled>รอผลประเมินให้ครบ</button>'} ${['SCREENING','DOCUMENT_CHECK'].includes(d.submission.status)?btn('decision','ไม่ผ่านการคัดกรอง',id):''}<h2>ไฟล์และเวอร์ชัน</h2>${fileButtons(d.files,'EDITOR')}<h2>ฉบับแก้ไข</h2>${d.revisions.map(r=>`<div class="result"><b>v${r.version} · ${date(r.submitted_at)}</b><pre>${E(JSON.stringify(JSON.parse(r.responses_json||'[]'),null,2))}</pre></div>`).join('')}<h2>ประวัติการตัดสิน</h2>${d.decisions.map(x=>`<p>${date(x.decided_at)} · ${E(x.type)} · ${E(x.message_to_author)}</p>`).join('')}${btn('letter','สร้างหนังสือตอบรับ PDF',id)} ${btn('withdraw','ถอนบทความ',id)}`);return;
      }
      if(which==='assign'){
        const reviewers=await api('listReviewers');context={manuscriptId:id};display(title('มอบหมายผู้ทรงคุณวุฒิ')+form('assignment',`<input name="manuscriptId" type="hidden" value="${E(id)}"><label>ค้นหาความเชี่ยวชาญ<input id="reviewerFilter" placeholder="พิมพ์ชื่อหรือความเชี่ยวชาญ"></label><div id="reviewerChoices">${reviewers.filter(r=>String(r.active)==='true').map(r=>`<label class="reviewer-choice"><input type="checkbox" name="reviewerId" value="${E(r.reviewer_id)}"><span><b>${E(r.name)}</b> · ${E(r.organization)}<br>${E(r.expertise)} · งานปัจจุบัน ${r.current} · เคยประเมิน ${r.completed}</span></label>`).join('')}</div><p id="reviewerCount">ต้องเลือกอย่างน้อย 2 คน</p>${field('dueAt','วันครบกำหนด','date')}${field('blindFile','PDF สำหรับประเมินที่ปกปิดข้อมูลผู้เขียนแล้ว','file')}<label class="reviewer-choice"><input type="checkbox" name="blindChecked" required><span>ตรวจชื่อผู้เขียน ข้อมูลติดต่อ สังกัด ชื่อไฟล์ metadata บทคัดย่อ และคำสำคัญแล้ว</span></label>`,'มอบหมายและเข้าคิวส่งคำเชิญ'));return;
      }
      if(which==='decision'){const d=await api('getDecisionContext',{manuscriptId:id});context=d;display(title('Editorial Decision')+`<p>${E(id)} · ${E(d.progress)} Reviews Complete</p><p>ตรวจผลประเมินและ confidential comments ในหน้ารายละเอียดก่อนตัดสิน</p>`+form('decision',`<input name="manuscriptId" type="hidden" value="${E(id)}">${select('decision','ผลตัดสิน',d.complete||d.submission.status==='REVISED'?rec:rec.filter(x=>x[0]==='REJECT'))}${text('message','ข้อความถึงผู้เขียน','',true)}${text('feedback','ข้อเสนอแนะนิรนามที่อนุญาตให้ผู้เขียนเห็น')}<label class="reviewer-choice"><input type="checkbox" name="feedbackChecked"><span>ตรวจแล้วว่าไม่มีชื่อผู้ประเมินหรือ confidential comments ในข้อความข้างต้น</span></label>${field('revisionDueAt','ครบกำหนดแก้ไข (เมื่อขอ Revision)','date','',false)}${text('internalNote','Internal Note — ไม่แสดงให้ผู้เขียน')}`,'ยืนยันผลตัดสิน'));return;}
      if(which==='author'){
        const d=await api('getAuthorWorkflow',{manuscriptId:id},'AUTHOR');context=d;
        const dec=d.decisions.map(x=>`<div class="result"><b>${E(x.type)} · ${date(x.at)}</b><p>${E(x.message)}</p><p class="journal-lines">${E(x.feedback)}</p>${x.dueAt?`<p>ครบกำหนดแก้ไข ${date(x.dueAt)}</p>`:''}</div>`).join('');
        display(title('ติดตามและดำเนินการบทความ')+btn('author-back','กลับบทความของฉัน')+`<h2>${E(d.title)}</h2><p>${E(id)} · ${E(d.status)} · v${d.version}</p>${dec}<h2>ไฟล์ของบทความ</h2>${fileButtons(d.files,'AUTHOR')}${d.status==='REVISION_REQUIRED'?`<h2>บทความของท่านต้องแก้ไข</h2>`+form('revision',`<input name="manuscriptId" type="hidden" value="${E(id)}">${field('wordFile','Word ฉบับแก้ไข (.docx)','file')}${field('pdfFile','PDF ฉบับแก้ไข','file')}<h3>Response to Reviewers</h3><div id="responseRows">${responseRow()}</div>${btn('add-response','เพิ่มแถวตอบข้อเสนอแนะ')} ${btn('save-response','บันทึกร่างคำตอบ')}${field('responseFile','Response Letter เพิ่มเติม (PDF/DOCX)','file','',false)}`,'ส่งบทความฉบับแก้ไข'):''}${d.status==='AUTHOR_PROOF'?form('author-proof',`<input name="manuscriptId" type="hidden" value="${E(id)}"><input name="version" type="hidden" value="${Math.max(...d.files.filter(f=>f.type==='FINAL_PDF').map(f=>f.version))}">${select('result','ผลตรวจ Final PDF',[['CONFIRMED','ยืนยันความถูกต้อง'],['CHANGES_REQUESTED','ขอแก้ไข']])}${text('message','รายละเอียดเมื่อขอแก้ไข')}`,'ส่งผลตรวจ Proof'):''}<h2>ประวัติฉบับแก้ไข</h2>${d.revisions.map(r=>`<p>Version ${r.version} · ${date(r.at)}</p>`).join('')}`);
        if(d.status==='REVISION_REQUIRED'){try{const saved=JSON.parse(localStorage.getItem('stjResponses:'+id)||'null');if(saved?.length)document.getElementById('responseRows').innerHTML=saved.map(responseRow).join('');}catch(e){}}
        return;
      }
      if(which==='production'){
        const d=await api('getProductionDashboard');context=d;display(title('ตรวจภาษา / จัดรูปแบบ')+d.rows.map(s=>`<div class="result"><h3>${E(s.title)}</h3><p>${E(s.manuscriptId)} · ${E(s.status)} · v${s.version}</p>${form('proof-check',`<input name="manuscriptId" type="hidden" value="${E(s.manuscriptId)}"><input name="version" type="hidden" value="${s.version}">${d.keys.map((k,i)=>`<label class="reviewer-choice"><input type="checkbox" name="check-${i}" ${JSON.parse(s.check?.checks_json||'[]')[i]?'checked':''}><span>${E(k)}</span></label>`).join('')}${text('note','หมายเหตุ',s.check?.note||'')}`,'บันทึก checklist')}${['PROOFREADING','PROOFREAD'].includes(s.status)?btn('to-layout','เปลี่ยนเป็นขั้นจัดรูปแบบ',s.manuscriptId):''}${s.status==='LAYOUT'?form('layout',`<input name="manuscriptId" type="hidden" value="${E(s.manuscriptId)}">${field('wordFile','Final DOCX','file')}${field('pdfFile','Final PDF','file')}`,'ส่งให้ผู้เขียนตรวจ Proof'):''}</div>`).join('')+(!d.rows.length?'<p>ยังไม่มีบทความตอบรับที่ได้รับมอบหมาย</p>':''));return;
      }
      if(which==='issues'){
        const d=await api('listIssues');context=d;display(title('ฉบับวารสาร')+form('issue',field('issue_id','Issue ID (ว่างสำหรับสร้างใหม่)','text','',false)+field('volume','ปีที่','number',1)+field('issue_number','ฉบับที่','number',1)+field('month','เดือน','text','มกราคม')+field('year_be','พ.ศ.','number',2570)+field('publication_date','วันที่กำหนดเผยแพร่','date','2027-01-01')+field('coverFile','ภาพปก PNG/JPG','file','',false)+text('description','คำอธิบาย')+select('status','สถานะ',[['Draft','ร่าง'],['Preparing','เตรียมฉบับ']]),'บันทึกฉบับ')+d.issues.map(i=>`<div class="result"><h3>ปีที่ ${i.volume} ฉบับที่ ${i.issue_number} ${E(i.month)} ${i.year_be}</h3><p>${E(i.issue_id)} · ${E(i.status)}</p>${d.articles.filter(a=>a.issue_id===i.issue_id).map(a=>`<p>${E(a.manuscript_id)} · หน้า ${a.page_start}–${a.page_end}</p>`).join('')}${i.status!=='Published'?form('issue-article',`<input name="issueId" type="hidden" value="${E(i.issue_id)}">${select('manuscriptId','บทความพร้อมเผยแพร่',d.ready.map(s=>[s.manuscriptId,s.title]))}${field('sequence','ลำดับ','number',1)}${field('pageStart','หน้าเริ่มต้น','number',1)}${field('pageEnd','หน้าสิ้นสุด','number',10)}`,'เพิ่ม / ปรับบทความในฉบับ')+btn('publish','ตรวจและเผยแพร่ฉบับ',i.issue_id):'<p>เผยแพร่แล้ว</p>'}</div>`).join(''));return;
      }
      if(which==='logs'){const d=await api('getJournalLogs');display(title('ประวัติและการแจ้งเตือน')+btn('flush-mail','ประมวลผลคิวอีเมล')+`<h2>รายการที่ต้องตรวจการกู้คืน</h2>${d.operations.map(o=>`<p>${E(o.action)} · ${E(o.operation_id)} · ${E(o.state)}</p>`).join('')||'<p>ไม่มีรายการค้าง</p>'}<h2>อีเมล</h2>${d.notifications.map(n=>`<p>${E(n.template)} · ${E(n.manuscript_id)} · ${E(n.status)} · ${date(n.sent_at)} ${E(n.safe_error)}</p>`).join('')}<h2>Audit Log (อ่านอย่างเดียว)</h2>${d.audit.map(a=>`<p>${date(a.occurred_at)} · ${E(a.user_id)} · ${E(a.role)} · ${E(a.action)} · ${E(a.manuscript_id)} · ${E(a.old_value)} → ${E(a.new_value)}</p>`).join('')}`);return;}
      if(which==='roles'){const d=await api('listStaffRoles');display(title('บทบาทและงานตรวจภาษา')+`<p>ใช้บัญชีผู้ใช้รายบุคคลที่สมัครแล้ว กองบรรณาธิการส่วนกลางยังใช้งานได้ตามเดิม</p>`+form('staff-role',select('userId','บัญชี',d.users.map(u=>[u.userId,u.name+' ('+u.username+')']))+select('role','บทบาท',[['PROOFREADER','ผู้ตรวจภาษา'],['EDITOR','บรรณาธิการ'],['MANAGING_EDITOR','บรรณาธิการบริหาร'],['ADMIN','ผู้ดูแล']])+select('active','การใช้งาน',[['true','เปิด'],['false','ปิด']])+field('manuscriptId','บทความที่มอบหมายให้ตรวจภาษา (ตอบรับแล้ว)','text','',false),'บันทึกบทบาท')+d.roles.map(r=>`<p>${E(r.user_id)} · ${E(r.role)} · ${E(r.active)}</p>`).join(''));return;}
      if(which==='letter'){display(title('หนังสือตอบรับ')+form('letter',`<input type="hidden" name="manuscriptId" value="${E(id)}">${field('letterNumber','เลขที่หนังสือ')}${field('editorName','ชื่อบรรณาธิการ')}`,'สร้างหนังสือตอบรับ PDF'));return;}
      if(which==='reviewer'){await reviewerDashboard();return;}
      if(which==='review-task'){const d=await api('getReviewerTask',{assignmentId:id},'REVIEWER');context=d;display(title(d.title)+`<p>${E(d.manuscriptId)} · ${E(d.type)}</p><h2>บทคัดย่อ</h2><p>${E(d.abstract)}</p><p>${E(d.abstractEn)}</p><p>${E(d.keywords)} · ${E(d.keywordsEn)}</p>${fileButtons([d.file],'REVIEWER')}${d.completed?`<div class="success">ส่งผลประเมินแล้ว ไม่สามารถแก้ไขได้โดยตรง กรุณาติดต่อกองบรรณาธิการ</div>`:form('review',`<input name="assignmentId" type="hidden" value="${E(id)}"><p>1 ควรปรับปรุงอย่างมาก · 2 ควรปรับปรุง · 3 ดี · 4 ดีมาก · 5 ดีเยี่ยม</p>${d.criteria.map((c,i)=>select('score-'+i,(i+1)+'. '+c,[[0,'เลือกคะแนน'],...[1,2,3,4,5].map(n=>[n,n])],d.draft?.scores?.[i]||0)).join('')}${text('strengths','จุดเด่น',d.draft?.strengths||'')}${text('suggestions','ข้อเสนอแนะเพื่อปรับปรุง',d.draft?.suggestions||'',true)}${text('comment_to_author','ข้อเสนอแนะเพิ่มเติมถึงผู้เขียน',d.draft?.comment_to_author||'')}${text('confidential_comment','Confidential Comment to Editor — ไม่แสดงให้ผู้เขียน',d.draft?.confidential_comment||'')}${select('recommendation','ผลสรุป',rec,d.draft?.recommendation)}${field('file','ไฟล์ข้อเสนอแนะ PDF/DOCX','file','',false)}${btn('review-draft','บันทึกร่าง')}`,'ส่งผลประเมิน')}`);return;}
    }catch(e){display(title('ไม่สามารถเปิดรายการได้')+`<p class="error">${E(e.message)}</p>${document.getElementById('journalPanel')?btn('setup','ตรวจการเตรียมระบบ'):''}`);}
  }
  function reviewerList(rows){return rows.map(r=>`<div class="result"><h3>${E(r.name)}</h3><p>${E(r.organization)} · ${E(r.expertise)}</p><p>${String(r.active)==='true'?'Active':'Inactive'} · งานปัจจุบัน ${r.current} · เคยประเมิน ${r.completed}</p>${btn('edit-reviewer','แก้ไข / เปิดปิด',r.reviewer_id)}<details><summary>ประวัติการประเมิน</summary>${r.history.map(a=>`<p>${E(a.manuscript_id)} · ${E(a.review_status)} · ${date(a.completed_at)}</p>`).join('')}</details></div>`).join('')||'<p>ยังไม่มีผู้ทรงคุณวุฒิ</p>';}
  function overview(d){return title('ภาพรวมกระบวนการวารสาร')+`<details open><summary>จำนวนตามสถานะ</summary><p>ทั้งหมด ${d.counts.ALL} · ผลประเมินครบ ${d.counts.REVIEW_COMPLETE}</p>${Object.entries(d.counts).filter(([s])=>!['ALL','REVIEW_COMPLETE'].includes(s)).map(([s,n])=>`<span class="tag">${E(d.states[s]||s)} ${n}</span> `).join('')}</details>`+form('overview-search',select('status','สถานะ',[['','ทุกสถานะ'],...Object.entries(d.states)])+select('type','ประเภท',[['','ทุกประเภท'],['RESEARCH','วิจัย'],['ACADEMIC','วิชาการ'],['INNOVATION','นวัตกรรม'],['STUDENT_PROJECT','IS / โครงงาน']])+field('department','กลุ่มสาระ','text','',false)+field('author','ผู้เขียน','text','',false)+field('fromDate','ตั้งแต่วันที่','date','',false)+field('toDate','ถึงวันที่','date','',false)+field('reviewerId','Reviewer ID','text','',false)+field('issueId','Issue ID','text','',false),'กรองรายการ')+d.rows.map(s=>`<div class="result"><h3>${E(s.title)}</h3><p>${E(s.manuscriptId)} · ${E(s.author)} · ${E(s.statusLabel)} ${s.reviewComplete?'· ผลประเมินครบ':''}</p>${btn('manuscript','เปิดรายละเอียด',s.manuscriptId)}</div>`).join('');}
  function reviewerForm(r){let expertise=r.expertise||'';try{const parsed=JSON.parse(expertise);if(Array.isArray(parsed))expertise=parsed.join(', ');}catch(e){}return title(r.reviewer_id?'แก้ไขผู้ทรงคุณวุฒิ':'เพิ่มผู้ทรงคุณวุฒิ')+form('reviewer-save',`<input name="reviewer_id" type="hidden" value="${E(r.reviewer_id||'')}">${['prefix','first_name','last_name','name','name_en','organization','position','qualification','subject_area','phone'].map((k,i)=>field(k,['คำนำหน้า','ชื่อ','นามสกุล','ชื่อแสดงผล','ชื่อภาษาอังกฤษ','สังกัด','ตำแหน่ง','วุฒิการศึกษา','กลุ่มสาระ/สาขา','โทรศัพท์'][i],'text',r[k]||'',k==='name')).join('')}${field('email','อีเมล','email',r.email||'')}${text('expertise','ความเชี่ยวชาญหลายด้าน (คั่นด้วยจุลภาค)',expertise)}${text('notes','หมายเหตุ',r.notes||'')}${select('active','สถานะ',[['true','Active'],['false','Inactive']],String(r.active??true))}`);}
  function responseRow(r={}){return `<div class="response-row">${text('comment','ข้อเสนอแนะ',r.comment||'',true)}${text('response','การแก้ไขของผู้เขียน',r.response||'',true)}${field('location','ตำแหน่งที่แก้ไข','text',r.location||'',false)}${field('page','หน้า','text',r.page||'',false)}${field('note','หมายเหตุ','text',r.note||'',false)}${btn('remove-response','ลบแถวนี้')}</div>`;}
  const responses=()=>Array.from(document.querySelectorAll('.response-row')).map(r=>Object.fromEntries(Array.from(r.querySelectorAll('input,textarea')).map(x=>[x.name,x.value])));
  const reviewData=f=>({scores:Array.from({length:15},(_,i)=>Number(f.elements['score-'+i].value)),strengths:f.elements.strengths.value,suggestions:f.elements.suggestions.value,comment_to_author:f.elements.comment_to_author.value,confidential_comment:f.elements.confidential_comment.value,recommendation:f.elements.recommendation.value});
  async function reviewerDashboard(){
    if(!reviewerToken){display(title('ผู้ทรงคุณวุฒิ')+form('reviewer-login',field('email','อีเมลที่ลงทะเบียน','email'),'ขอลิงก์เข้าสู่ระบบ'));return;}
    const d=await api('getReviewerDashboard',{},'REVIEWER');display(title('Reviewer Dashboard')+btn('reviewer-out','ออกจากระบบ')+d.tasks.map(a=>`<div class="result"><h3>${E(a.title)}</h3><p>${E(a.manuscriptId)} · ${E(a.type)} · รอบ ${a.round}</p><p>เชิญ ${date(a.assignedAt)} · ครบกำหนด ${date(a.dueAt)}</p><p>${E(a.invitationStatus)} · ${E(a.reviewStatus)}</p>${a.invitationStatus==='Pending'?btn('accept-invite','ตอบรับการประเมิน',a.assignmentId)+' '+btn('decline-invite','ปฏิเสธการประเมิน',a.assignmentId):a.invitationStatus==='Accepted'?btn('review-task',a.reviewStatus==='Completed'?'ดูผลที่ส่งแล้ว':'ประเมินบทความ',a.assignmentId):''}</div>`).join(''));
  }
  document.addEventListener('click',async ev=>{
    const b=ev.target.closest('[data-j-action]');if(!b)return;const a=b.dataset.jAction,id=b.dataset.id;b.disabled=true;
    try{
      if(a.startsWith('file-')){await download(id,a.slice(5));return;}
      if(a==='author-back'){window.view('account');return;}
      if(a==='initialize'){if(!confirm('ยืนยันสำรองข้อมูล จำกัดสิทธิ์การแชร์ และเตรียมระบบวารสาร?'))return;const logo=await (await fetch('assets/school-logo.png')).blob(),base64=await new Promise((resolve,reject)=>{const r=new FileReader();r.onload=()=>resolve(r.result.split(',')[1]);r.onerror=reject;r.readAsDataURL(logo);});await api('setupJournal',{logoFile:{name:'school-logo.png',base64}});message('สำรองข้อมูลและเตรียมระบบสำเร็จ');return;}
      if(a==='new-reviewer'){display(reviewerForm({}));return;}
      if(a==='edit-reviewer'){const r=context.find(r=>r.reviewer_id===id);display(reviewerForm(r));return;}
      if(a==='cancel-assignment'){const reason=prompt('เหตุผลที่ยกเลิกงานประเมิน');if(!reason||!confirm('ยืนยันยกเลิกงานนี้?'))return;await api('cancelAssignment',{assignmentId:id,reason,operationId:crypto.randomUUID()});await open('manuscript',context.submission.manuscript_id);return;}
      if(a==='withdraw'){const reason=prompt('เหตุผลที่ถอนบทความ');if(!reason||!confirm('ยืนยันถอนบทความ โดยเก็บประวัติเดิมไว้?'))return;await api('withdrawManuscript',{manuscriptId:id,reason,operationId:crypto.randomUUID()});await open('manuscript',id);return;}
      if(a==='add-response'){document.getElementById('responseRows').insertAdjacentHTML('beforeend',responseRow());return;}
      if(a==='remove-response'){b.closest('.response-row').remove();return;}
      if(a==='save-response'){localStorage.setItem('stjResponses:'+context.manuscriptId,JSON.stringify(responses()));message('บันทึกร่างคำตอบแล้วในเบราว์เซอร์นี้');return;}
      if(a==='review-draft'){await api('saveReviewDraft',{assignmentId:context.assignmentId,data:reviewData(b.closest('form')),operationId:crypto.randomUUID()},'REVIEWER');message('บันทึกร่างผลประเมินแล้ว');return;}
      if(a==='to-layout'){if(!confirm('ยืนยัน checklist ครบ และเปลี่ยนเป็นขั้นจัดรูปแบบ?'))return;await api('updateSubmissionStatus',{manuscriptId:id,status:'LAYOUT',operationId:crypto.randomUUID()});await open('production');return;}
      if(a==='publish'){await api('validatePublication',{issueId:id});if(!confirm('ยืนยันเผยแพร่ฉบับและบทความทั้งหมดสู่สาธารณะ?'))return;await api('publishIssue',{issueId:id,operationId:crypto.randomUUID()});await open('issues');message('เผยแพร่สำเร็จ');return;}
      if(a==='flush-mail'){if(!confirm('ประมวลผลคิวและส่งอีเมลถึงผู้รับที่บันทึกไว้?'))return;await api('flushJournalNotifications');await open('logs');return;}
      if(a==='accept-invite'||a==='decline-invite'){const reason=a==='decline-invite'?prompt('เหตุผล: ไม่มีเวลา / ไม่ตรงความเชี่ยวชาญ / Conflict of Interest / รู้จักผู้เขียน / อื่น ๆ'):'';if(a==='decline-invite'&&!reason)return;if(!confirm('ยืนยันคำตอบคำเชิญ?'))return;await api('respondToInvitation',{assignmentId:id,response:a==='accept-invite'?'Accepted':'Declined',reason,operationId:crypto.randomUUID()},'REVIEWER');await reviewerDashboard();return;}
      if(a==='reviewer-out'){await api('reviewerLogout',{},'REVIEWER');reviewerToken='';sessionStorage.removeItem('stjReviewerToken');await reviewerDashboard();return;}
      if(a==='staff-enter'){window.token=author();sessionStorage.setItem('stjToken',author());window.view('editor');return;}
      await open(a,id);
    }catch(e){message(e.message,true);}finally{b.disabled=false;}
  });
  document.addEventListener('submit',async ev=>{
    const f=ev.target.closest('[data-j-form]');if(!f)return;ev.preventDefault();const a=f.dataset.jForm,b=f.querySelector('[type=submit]');if(b.disabled)return;b.disabled=true;
    try{
      const p=await stjFormPayload(f),op=crypto.randomUUID();
      if(a==='open-manuscript'){await open('manuscript',p.manuscriptId);return;}
      if(a==='overview-search'){const d=await api('getJournalOverview',p);display(overview(d));return;}
      if(a==='reviewer-search'){const r=await api('listReviewers',p);context=r;display(title('ผู้ทรงคุณวุฒิ')+reviewerList(r)+btn('reviewers','ค้นหาใหม่')+btn('new-reviewer','เพิ่มผู้ทรงคุณวุฒิ'));return;}
      if(a==='reviewer-login'){const r=await stjApi('requestReviewerLogin',{email:p.email});message(r.message);return;}
      const confirmation=a==='review'?'เมื่อส่งผลประเมินแล้วจะไม่สามารถแก้ไขได้โดยตรง หากต้องการแก้ไขกรุณาติดต่อกองบรรณาธิการ ยืนยันส่งผลประเมิน?':'ยืนยันบันทึกและดำเนินการรายการนี้?';if(!confirm(confirmation))return;
      if(a==='reviewer-save'){await api('saveReviewer',{data:p,operationId:op});await open('reviewers');}
      else if(a==='assignment'){await api('assignReviewers',{manuscriptId:p.manuscriptId,reviewerIds:new FormData(f).getAll('reviewerId'),dueAt:p.dueAt,blindFile:p.blindFile,blindChecked:!!p.blindChecked,operationId:op});await open('manuscript',p.manuscriptId);}
      else if(a==='decision'){await api('submitEditorialDecision',{...p,feedbackChecked:!!p.feedbackChecked,operationId:op});await open('manuscript',p.manuscriptId);}
      else if(a==='revision'){await api('submitRevision',{...p,responses:responses(),operationId:op},'AUTHOR');localStorage.removeItem('stjResponses:'+p.manuscriptId);await open('author',p.manuscriptId);}
      else if(a==='author-proof'){await api('submitAuthorProof',{...p,operationId:op},'AUTHOR');await open('author',p.manuscriptId);}
      else if(a==='proof-check'){await api('saveProofChecklist',{...p,checks:Array.from({length:10},(_,i)=>!!p['check-'+i]),operationId:op});await open('production');}
      else if(a==='layout'){await api('uploadLayout',{...p,operationId:op});await open('production');}
      else if(a==='issue'){await api('saveIssue',{data:p,coverFile:p.coverFile,operationId:op});await open('issues');}
      else if(a==='issue-article'){await api('assignIssueArticle',{...p,operationId:op});await open('issues');}
      else if(a==='letter'){const r=await api('createAcceptanceLetter',{...p,operationId:op});await download(r.fileId);message('สร้างหนังสือตอบรับแล้ว');}
      else if(a==='staff-role'){await api('grantStaffRole',{...p,active:p.active==='true',operationId:op});await open('roles');}
      else if(a==='review'){await api('submitReview',{assignmentId:p.assignmentId,data:reviewData(f),file:p.file,operationId:op},'REVIEWER');await open('review-task',p.assignmentId);}
      message('ดำเนินการสำเร็จ');
    }catch(e){message(e.message,true);}finally{b.disabled=false;}
  });
  document.addEventListener('input',ev=>{
    if(ev.target.id==='reviewerFilter'){const q=ev.target.value.toLowerCase();document.querySelectorAll('.reviewer-choice').forEach(n=>{if(n.querySelector('[name=reviewerId]'))n.hidden=!n.textContent.toLowerCase().includes(q);});}
    if(ev.target.name==='reviewerId'){const count=document.querySelectorAll('[name=reviewerId]:checked').length;document.getElementById('reviewerCount').textContent=count<2?'เลือก '+count+' คน — ต้องเลือกอย่างน้อย 2 คน':'เลือก '+count+' คน';}
  });
  document.addEventListener('DOMContentLoaded',async()=>{
    const dashboard=document.getElementById('dashboard');
    if(dashboard){dashboard.insertAdjacentHTML('afterbegin',`<nav class="journal-nav" aria-label="กระบวนการวารสาร">${[['overview','ภาพรวม workflow'],['reviewers','ผู้ทรงคุณวุฒิ'],['manuscript','ประเมิน / ตัดสิน'],['production','ตรวจภาษา / จัดรูปแบบ'],['issues','ฉบับวารสาร'],['roles','บทบาทบุคลากร'],['logs','ประวัติ / อีเมล'],['setup','เตรียมระบบ']].map(([a,l])=>btn(a,l)).join('')}</nav>`);document.querySelector('main').insertAdjacentHTML('beforeend','<section id="journalPanel" class="view"><nav class="journal-nav">'+btn('reviewers','ผู้ทรงคุณวุฒิ')+btn('manuscript','ประเมิน / ตัดสิน')+btn('production','งานผลิต')+btn('issues','ฉบับวารสาร')+btn('logs','ประวัติ')+'<button type="button" onclick="view(\'editor\')">กลับ Dashboard</button></nav><div id="journalContent"></div></section>');root=document.getElementById('journalContent');
      const mine=document.getElementById('myManuscripts');new MutationObserver(()=>{mine.querySelectorAll('.result').forEach(n=>{if(n.querySelector('[data-j-action]'))return;const id=n.querySelector('h3')?.textContent;if(id)n.insertAdjacentHTML('beforeend',btn('author','ดูไฟล์ / แก้ไข / ตรวจ Proof',id));});}).observe(mine,{childList:true});
      document.getElementById('myAccount').insertAdjacentHTML('beforeend',btn('staff-enter','เข้าเมนูบุคลากร (ตามสิทธิ์ที่ได้รับ)'));
      document.getElementById('submissionForm').addEventListener('submit',e=>{if(!confirm('ยืนยันส่งบทความเข้าสู่การพิจารณาของวารสาร?')){e.preventDefault();e.stopImmediatePropagation();}},true);
      if(location.hash==='#journal')await open('manuscript');
    }else{root=document.getElementById('reviewerRoot');if(!root)return;const match=location.hash.match(/^#invite=([a-zA-Z0-9-]+)$/);if(match){history.replaceState(null,'',location.pathname);try{const r=await stjApi('exchangeReviewerToken',{invitationToken:match[1]});reviewerToken=r.token;sessionStorage.setItem('stjReviewerToken',r.token);}catch(e){display(title('คำเชิญผู้ทรงคุณวุฒิ')+`<p class="error">${E(e.message)}</p>`+btn('reviewer','ขอลิงก์ใหม่'));return;}}await open('reviewer');}
  });
  window.Journal={open};
})();
