(function(){
  const E=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const date=v=>v?new Date(v).toLocaleDateString('th-TH'):'—';
  async function file(id,cover=false){const f=await stjApi('getAuthorizedFile',{fileId:id}),bytes=Uint8Array.from(atob(f.base64),c=>c.charCodeAt(0)),url=URL.createObjectURL(new Blob([bytes],{type:f.mime}));if(cover){const img=document.getElementById('issueCover');if(img){img.src=url;img.hidden=false;img.onload=()=>URL.revokeObjectURL(url);}return;}const a=document.createElement('a');a.href=url;a.download=f.name;a.click();setTimeout(()=>URL.revokeObjectURL(url),10000);}
  async function render(){const root=document.getElementById('publicationRoot');root.innerHTML='<p>กำลังโหลดข้อมูลวารสาร…</p>';try{const hash=location.hash.slice(1),params=new URLSearchParams(hash),data=await stjApi('getPublicJournal',{issueId:params.get('issue')||'',manuscriptId:params.get('article')||''});
    if(hash==='archives'){root.innerHTML='<h1>ฉบับย้อนหลัง</h1>'+data.issues.map(i=>`<div class="result"><h2><a href="#issue=${E(i.issueId)}">ปีที่ ${i.volume} ฉบับที่ ${i.issue} ${E(i.month)} ${i.yearBE}</a></h2><p>เผยแพร่ ${date(i.date)}</p></div>`).join('')+(!data.issues.length?'<p>ยังไม่มีฉบับเผยแพร่ ฉบับแรกกำหนดเดือนมกราคม 2570</p>':'');return;}
    if(params.get('article')){const a=data.articles[0];if(!a){root.innerHTML='<h1>ไม่พบบทความที่เผยแพร่</h1>';return;}root.innerHTML=`<article class="panel"><h1>${E(a.title)}</h1><h2 lang="en">${E(a.titleEn)}</h2><p>${a.authors.map(x=>E(x.name)+(x.affiliation?' · '+E(x.affiliation):'')).join('<br>')}</p><p>${E(a.type)} · ปีที่ ${a.volume} ฉบับที่ ${a.issue} · หน้า ${E(a.pages)}</p><h2>บทคัดย่อ</h2><p>${E(a.abstract)}</p><p><b>คำสำคัญ:</b> ${E(a.keywords)}</p><h2>Abstract</h2><p lang="en">${E(a.abstractEn)}</p><p><b>Keywords:</b> ${E(a.keywordsEn)}</p><p>Received: ${date(a.received)} · Revised: ${date(a.revised)} · Accepted: ${date(a.accepted)} · Published: ${date(a.published)}</p><button data-pdf="${E(a.pdfFileId)}">ดาวน์โหลด PDF</button></article>`;return;}
    const i=data.current;root.innerHTML='<h1>ฉบับปัจจุบัน</h1>'+(!i?'<div class="panel"><h2>ปีที่ 1 ฉบับที่ 1 มกราคม 2570</h2><p>อยู่ระหว่างเตรียมฉบับ ยังไม่ได้เผยแพร่บทความ</p></div>':`<section class="panel"><h2>ปีที่ ${i.volume} ฉบับที่ ${i.issue} ${E(i.month)} ${i.yearBE}</h2><img id="issueCover" hidden alt="หน้าปกฉบับวารสาร" style="max-width:240px;width:100%"><p>${E(i.description)}</p><h2>สารบัญ</h2>${data.articles.map(a=>`<div class="result"><h3><a href="#article=${E(a.manuscriptId)}">${E(a.title)}</a></h3><p>${a.authors.map(x=>E(x.name)).join(', ')} · ${E(a.type)} · หน้า ${E(a.pages)}</p><a href="#article=${E(a.manuscriptId)}">อ่านบทความ</a> <button data-pdf="${E(a.pdfFileId)}">PDF</button></div>`).join('')}</section>`);if(i?.coverFileId)await file(i.coverFileId,true);
  }catch(e){root.innerHTML=`<p class="error">${E(e.message)}</p>`;}}
  document.addEventListener('DOMContentLoaded',render);window.addEventListener('hashchange',render);document.addEventListener('click',async e=>{const b=e.target.closest('[data-pdf]');if(!b)return;b.disabled=true;try{await file(b.dataset.pdf);}catch(err){document.getElementById('publicationError').textContent=err.message;}finally{b.disabled=false;}});
})();
