// Full lifecycle on isolated in-memory Google services. Never contacts production or sends email.
const assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm'),crypto=require('node:crypto');
const {context:c,sheets,properties,Folder,files,root,form,owner,other,ss,ok,reject}=require('./integration.test');
c.console.error=()=>{}; const permissions=new Map(),sent=[];let backups=0,triggered=0;
const iterator=rows=>({hasNext:()=>rows.length>0,next:()=>rows.shift()});
const blob=(bytes,mime='application/pdf',name='file.pdf')=>({getName:()=>name,setName:n=>name=n,getBytes:()=>Array.from(bytes),getContentType:()=>mime,getAs:()=>blob(Buffer.from('%PDF-generated letter'),'application/pdf','letter.pdf')});
const fileWrapper=f=>({getId:()=>f.id,getName:()=>f.name,getBlob:()=>blob(f.bytes||Buffer.from('%PDF-test'),f.mime||'application/pdf',f.name),setSharing:(a,p)=>{permissions.set(f.id,a);return fileWrapper(f);},makeCopy:(name,folder)=>folder.createFile(blob(f.bytes||Buffer.from('%PDF-test'),f.mime,name))});
Folder.prototype.getName=function(){return this.name;}; Folder.prototype.setSharing=function(a){permissions.set(this.id,a);return this;};
Folder.prototype.getFiles=function(){return iterator(files.filter(f=>f.folder===this.id).map(fileWrapper));};
Folder.prototype.getFolders=function(){return iterator([...this.children]);};
Folder.prototype.createFile=function(b){const f={id:crypto.randomUUID(),name:b.getName(),folder:this.id,bytes:Buffer.from(b.getBytes()),mime:b.getContentType()};files.push(f);return fileWrapper(f);};
c.DriveApp.Access={PRIVATE:'PRIVATE'};c.DriveApp.Permission={NONE:'NONE'};
c.DriveApp.createFolder=name=>new Folder(name);
c.DriveApp.getFileById=id=>fileWrapper(files.find(f=>f.id===id)||{id,name:'Database'});
ss.copy=name=>{backups++;const data=Array.from(sheets,([n,s])=>[n,JSON.stringify(s.data)]);return {getId:()=> 'backup-'+backups,data};};
c.ScriptApp={getProjectTriggers:()=>[],newTrigger:()=>({timeBased(){return this;},everyHours(){return this;},create(){triggered++;}})};
c.Utilities.newBlob=(b,m,n)=>blob(Buffer.from(b),m,n);
c.Utilities.base64Decode=value=>Array.from(Buffer.from(value,'base64'));
c.Utilities.base64Encode=bytes=>Buffer.from(bytes).toString('base64');
c.Utilities.computeDigest=(_,v)=>Array.from(crypto.createHash('sha256').update(typeof v==='string'?v:Buffer.from(v)).digest()).map(b=>b>127?b-256:b);
c.Utilities.formatDate=d=>new Date(d).toISOString().slice(0,10);
c.LockService.getScriptLock=()=>({waitLock(){},tryLock(){return true;},releaseLock(){}});
c.MailApp={getRemainingDailyQuota:()=>100,sendEmail:m=>sent.push(m)};
for(const name of ['Journal','Notifications','PeerReview','Revisions','Production','Issues'])vm.runInContext(fs.readFileSync('backend/apps-script/'+name+'.gs','utf8'),c,{filename:name+'.gs'});
const op=()=>crypto.randomUUID(),call=(n,p={})=>c[n](p),editor=ok(call('editorLogin',{password:'123456'})).token;
const edit={token:editor},author={token:owner.token},authorB={token:other.token};
const before=sheets.get('SUBMISSIONS').data.length;
ok(call('setupJournal',edit));assert.equal(backups,1);assert.equal(triggered,1);assert.equal(permissions.get('test-sheet'),'PRIVATE');
ok(call('setupJournal',edit));assert.equal(backups,1);assert.equal(sheets.get('SUBMISSIONS').data.length,before);
const headers=sheets.get('REVIEWERS').data[0].join('|');assert.equal(headers,'reviewer_id|name|email|organization|expertise|active');
const initial=ok(call('submitManuscript',{...form(),word_file:blob(Buffer.from('PK-word'),'application/vnd.openxmlformats-officedocument.wordprocessingml.document','initial.docx'),pdf_file:blob(Buffer.from('%PDF-initial'),'application/pdf','initial.pdf'),abstract_th:'บทคัดย่อเพื่อทดสอบ',abstract_en:'Test abstract'}));
const id=initial.manuscriptId;
const change=s=>ok(call('updateSubmissionStatus',{...edit,manuscriptId:id,status:s,operationId:op()}));
reject(call('getAuthorWorkflow',{...authorB,manuscriptId:id}));
change('DOCUMENT_CHECK');change('SCREENING');
reject(call('updateSubmissionStatus',{...edit,manuscriptId:id,status:'ACCEPTED',operationId:op()}));
const r1=ok(call('saveReviewer',{...edit,operationId:op(),data:{name:'Reviewer SECRET ONE',email:'reviewer-one@example.invalid',expertise:'วิทยาศาสตร์,วิจัย',active:true}})).reviewerId;
const r2=ok(call('saveReviewer',{...edit,operationId:op(),data:{name:'Reviewer SECRET TWO',email:'reviewer-two@example.invalid',active:true}})).reviewerId;
const r3=ok(call('saveReviewer',{...edit,operationId:op(),data:{name:'Inactive',email:'reviewer-three@example.invalid',active:false}})).reviewerId;
const upload=(name,data='%PDF-test manuscript')=>({name,base64:Buffer.from(data).toString('base64')});
const assignment={...edit,manuscriptId:id,reviewerIds:[r1,r2],dueAt:new Date(Date.now()+10*86400000).toISOString(),blindFile:upload('blind.pdf'),blindChecked:true};
reject(call('assignReviewers',{...assignment,reviewerIds:[r1],operationId:op()}));
reject(call('assignReviewers',{...assignment,reviewerIds:[r1,r1],operationId:op()}));
reject(call('assignReviewers',{...assignment,reviewerIds:[r1,r3],operationId:op()}));
const ao=op(),assigned=ok(call('assignReviewers',{...assignment,operationId:ao}));
assert.equal(ok(call('assignReviewers',{...assignment,operationId:ao})).assignments[0],assigned.assignments[0]);
assert.equal(c.jRows_('REVIEW_ASSIGNMENTS').filter(a=>a.manuscript_id===id).length,2);
const raw1=c.jToken_(r1,assigned.assignments[0],'INVITATION'),raw2=c.jToken_(r2,assigned.assignments[1],'INVITATION');
const t1=ok(call('exchangeReviewerToken',{invitationToken:raw1})).token,t2=ok(call('exchangeReviewerToken',{invitationToken:raw2})).token;
reject(call('exchangeReviewerToken',{invitationToken:raw1}));assert.ok(!JSON.stringify(c.jRows_('ACCESS_TOKENS')).includes(raw1));
ok(call('respondToInvitation',{token:t1,assignmentId:assigned.assignments[0],response:'Accepted',operationId:op()}));
reject(call('getReviewerTask',{token:t1,assignmentId:assigned.assignments[1]}));
reject(call('getDashboard',{token:t1}));
ok(call('respondToInvitation',{token:t2,assignmentId:assigned.assignments[1],response:'Accepted',operationId:op()}));
const task=ok(call('getReviewerTask',{token:t1,assignmentId:assigned.assignments[0]}));
assert.equal(task.authors,undefined);assert.equal(task.submission,undefined);assert.ok(!JSON.stringify(task).includes('qa@example.com'));
const result={scores:Array(15).fill(4),recommendation:'MAJOR',suggestions:'Improve methodology',confidential_comment:'CONFIDENTIAL SECRET'};
const review={token:t1,assignmentId:assigned.assignments[0],data:result,operationId:op()};
reject(call('submitReview',{...review,data:{...result,scores:[4]}}));
ok(call('saveReviewDraft',{...review,operationId:op()}));ok(call('submitReview',review));ok(call('submitReview',review));
reject(call('submitReview',{...review,operationId:op()}));reject(call('saveReviewDraft',{...review,operationId:op()}));
assert.equal(ok(call('getDecisionContext',{...edit,manuscriptId:id})).progress,'1/2');
ok(call('submitReview',{token:t2,assignmentId:assigned.assignments[1],data:{...result,recommendation:'MINOR'},operationId:op()}));
assert.equal(ok(call('getDecisionContext',{...edit,manuscriptId:id})).complete,true);
ok(call('submitEditorialDecision',{...edit,manuscriptId:id,decision:'MAJOR',message:'Please revise',internalNote:'INTERNAL SECRET',feedback:'Anonymous feedback',feedbackChecked:true,revisionDueAt:new Date(Date.now()+20*86400000).toISOString(),operationId:op()}));
const av=ok(call('getAuthorWorkflow',{...author,manuscriptId:id}));const avjson=JSON.stringify(av);assert.ok(!avjson.includes('CONFIDENTIAL SECRET'));assert.ok(!avjson.includes('INTERNAL SECRET'));assert.ok(!avjson.includes('Reviewer SECRET'));
const rev={...author,manuscriptId:id,wordFile:upload('revision.docx','PK-test word'),pdfFile:upload('revision.pdf'),responses:[{comment:'Improve methodology',response:'Updated',page:'3'}],operationId:op()};
reject(call('submitRevision',{...rev,...authorB}));ok(call('submitRevision',rev));ok(call('submitRevision',rev));assert.equal(c.jRows_('REVISIONS').filter(r=>r.manuscript_id===id).length,1);
ok(call('submitEditorialDecision',{...edit,manuscriptId:id,decision:'ACCEPT',message:'Accepted',operationId:op()}));
const letters=ok(call('createAcceptanceLetter',{...edit,manuscriptId:id,editorName:'Editor',letterNumber:'STJ/001',operationId:op()}));assert.ok(letters.fileId);
const staffUid=other.userId||c.requireAuthor_(other.token);
ok(call('grantStaffRole',{...edit,userId:staffUid,role:'PROOFREADER',manuscriptId:id,operationId:op()}));
const prod=ok(call('getProductionDashboard',{...authorB}));assert.ok(prod.rows.some(s=>s.manuscriptId===id));
reject(call('saveProofChecklist',{...authorB,manuscriptId:before,version:2,checks:Array(10).fill(true),operationId:op()}));
ok(call('saveProofChecklist',{...authorB,manuscriptId:id,version:2,checks:Array(10).fill(true),operationId:op()}));change('LAYOUT');
const layout=ok(call('uploadLayout',{...edit,manuscriptId:id,wordFile:upload('final.docx','PK-final'),pdfFile:upload('final.pdf'),operationId:op()}));
reject(call('submitAuthorProof',{...authorB,manuscriptId:id,version:layout.proofVersion,result:'CONFIRMED',operationId:op()}));
ok(call('submitAuthorProof',{...author,manuscriptId:id,version:layout.proofVersion,result:'CHANGES_REQUESTED',message:'Correct a table',operationId:op()}));
reject(call('uploadLayout',{...edit,manuscriptId:id,wordFile:upload('final.docx','PK-final'),pdfFile:upload('final.pdf'),operationId:op()}));
ok(call('saveProofChecklist',{...edit,manuscriptId:id,version:2,checks:Array(10).fill(true),operationId:op()}));
const layout2=ok(call('uploadLayout',{...edit,manuscriptId:id,wordFile:upload('final.docx','PK-final'),pdfFile:upload('final.pdf'),operationId:op()}));
assert.ok(layout2.proofVersion>layout.proofVersion);
reject(call('submitAuthorProof',{...author,manuscriptId:id,version:layout.proofVersion,result:'CONFIRMED',operationId:op()}));
ok(call('submitAuthorProof',{...author,manuscriptId:id,version:layout2.proofVersion,result:'CONFIRMED',operationId:op()}));
const issue=ok(call('saveIssue',{...edit,data:{volume:1,issue_number:1,month:'มกราคม',year_be:2570,publication_date:'2026-01-01'},operationId:op()})).issueId;
reject(call('publishIssue',{...edit,issueId:issue,operationId:op()}));
ok(call('assignIssueArticle',{...edit,issueId:issue,manuscriptId:id,pageStart:1,pageEnd:10,sequence:1,operationId:op()}));
assert.equal(ok(call('getPublicJournal',{})).issues.length,0);
ok(call('publishIssue',{...edit,issueId:issue,operationId:op()}));
const pub=ok(call('getPublicJournal',{}));assert.equal(pub.issues.length,1);assert.equal(pub.articles[0].manuscriptId,id);
assert.ok(!JSON.stringify(pub).includes('qa@example.com'));assert.ok(!JSON.stringify(pub).includes('Reviewer SECRET'));assert.ok(!JSON.stringify(pub).includes('CONFIDENTIAL SECRET'));
ok(call('getAuthorizedFile',{fileId:pub.articles[0].pdfFileId}));reject(call('getAuthorizedFile',{fileId:task.file.fileId}));reject(call('getAuthorizedFile',{...author,fileId:task.file.fileId}));
ok(call('getAuthorizedFile',{token:t1,fileId:task.file.fileId}));
const wrongSignature=upload('fake.pdf','not pdf');assert.throws(()=>c.jSaveFile_(c.jManuscript_(id),{id:'x'},wrongSignature,'FINAL_PDF',99,'AUTHOR'));
c.processJournalJobs_();const sentCount=sent.length;c.processJournalJobs_();assert.equal(sent.length,sentCount);
assert.ok(c.jRows_('AUDIT_LOG').length>20);assert.ok(c.jRows_('NOTIFICATIONS').every(n=>!n.body.includes(raw1)));
reject(call('withdrawManuscript',{...edit,manuscriptId:id,reason:'test',operationId:op()}));
const r4=ok(call('saveReviewer',{...edit,operationId:op(),data:{name:'Third reviewer',email:'third@example.invalid',active:true}})).reviewerId;
const id2=ok(call('submitManuscript',{...form(),word_file:blob(Buffer.from('PK-word'),'application/vnd.openxmlformats-officedocument.wordprocessingml.document','initial.docx'),pdf_file:blob(Buffer.from('%PDF-initial'),'application/pdf','initial.pdf')})).manuscriptId;
for(const status of ['DOCUMENT_CHECK','SCREENING'])ok(call('updateSubmissionStatus',{...edit,manuscriptId:id2,status,operationId:op()}));
const three=ok(call('assignReviewers',{...assignment,manuscriptId:id2,reviewerIds:[r1,r2,r4],dueAt:new Date(Date.now()+3*86400000).toISOString(),operationId:op()}));
assert.equal(ok(call('getDecisionContext',{...edit,manuscriptId:id2})).progress,'0/3');
for(const [token,assignmentId] of [[t1,three.assignments[0]],[t2,three.assignments[1]]])ok(call('respondToInvitation',{token,assignmentId,response:'Accepted',operationId:op()}));
c.processJournalJobs_();const reminderCount=c.jRows_('REMINDER_LOG').length;assert.equal(reminderCount,2);assert.ok(c.jRows_('REMINDER_LOG').every(r=>r.queued_at&&r.sent_at));c.processJournalJobs_();assert.equal(c.jRows_('REMINDER_LOG').length,reminderCount);
const inactiveToken=c.jToken_(r4,three.assignments[2],'INVITATION');
ok(call('saveReviewer',{...edit,operationId:op(),data:{reviewer_id:r4,name:'Third reviewer',email:'third@example.invalid',active:false}}));
reject(call('exchangeReviewerToken',{invitationToken:inactiveToken}));
ok(call('grantStaffRole',{...edit,userId:staffUid,role:'EDITOR',operationId:op()}));
reject(call('grantStaffRole',{...authorB,userId:staffUid,role:'ADMIN',operationId:op()}));
reject(call('submitEditorialDecision',{...edit,manuscriptId:id2,decision:'ACCEPT',message:'Should not accept early',operationId:op()}));
console.log('PASS full journal lifecycle: backup/restriction, legacy schema, two blind reviews, confidentiality, revision versions, acceptance, named proofreader, proof, issue, publication, private downloads, audit and email dedupe');
module.exports={c,editor,owner,id,t1,task,pub};




