var SHEETS_ = {
  SUBMISSIONS:['manuscript_id','submitted_at','title_th','title_en','article_type','department','keywords_th','keywords_en','abstract_th','abstract_en','work_origin','previously_published','previous_publication_details','ai_used','ai_tools','ai_purposes','ai_details','human_data_used','participant_groups','ethics_document_status','status','public_note','private_note','drive_folder_id','word_file_id','pdf_file_id','certificate_file_id','ai_disclosure_file_id','ethics_file_id','updated_at'],
  AUTHORS:['manuscript_id','author_order','is_corresponding','name_th','name_en','role','department','email','phone','grade_level','classroom','advisor_name','advisor_department'],
  STATUS_LOG:['manuscript_id','changed_at','from_status','to_status','public_note','private_note','actor'],
  SETTINGS:['key','value','description'], REVIEWERS:['reviewer_id','name','email','organization','expertise','active'], REVIEWS:['review_id','manuscript_id','reviewer_id','status','assigned_at','submitted_at','recommendation']
};
function doGet(e){if(properties_().getProperty('DATABASE_READY')!=='true'){setupSystem();properties_().setProperty('DATABASE_READY','true');}if(e&&e.parameter&&e.parameter.bridge==='1'){var page=HtmlService.createTemplateFromFile('Bridge');page.channel=/^[a-f0-9-]{36}$/.test(String(e.parameter.channel||''))?e.parameter.channel:'';return page.evaluate().setTitle('STJ Data Bridge').setXFrameOptionsMode(HtmlService.XFrameOptionsMode.ALLOWALL);}return HtmlService.createHtmlOutputFromFile('Index').setTitle('STJ Submission').addMetaTag('viewport','width=device-width, initial-scale=1');}
function response_(fn){try{return {ok:true,data:JSON.parse(JSON.stringify(fn()))};}catch(e){console.error(e&&e.stack?e.stack:e);return {ok:false,error:e&&e.publicMessage?e.publicMessage:'ระบบไม่สามารถดำเนินการได้ กรุณาลองใหม่หรือติดต่อกองบรรณาธิการ'};}}
function properties_(){return PropertiesService.getScriptProperties();}
function requiredProperty_(key){var value=properties_().getProperty(key);if(!value)throw new Error('ยังไม่ได้ตั้งค่า '+key);return value;}
function spreadsheet_(){return SpreadsheetApp.openById(requiredProperty_('SPREADSHEET_ID'));}
function sheet_(name){var sheet=spreadsheet_().getSheetByName(name);if(!sheet)throw new Error('ไม่พบชีต '+name);return sheet;}
function rows_(name){var values=sheet_(name).getDataRange().getValues();if(values.length<2)return[];var headers=values[0].map(String);return values.slice(1).filter(function(r){return r.some(function(v){return v!==''&&v!==null;});}).map(function(r,i){var o={_row:i+2};headers.forEach(function(h,j){o[h]=r[j];});return o;});}
function append_(name,obj){sheet_(name).appendRow(SHEETS_[name].map(function(h){return safeCell_(obj[h]);}));}
function update_(name,row,obj){var headers=SHEETS_[name],sh=sheet_(name),old=sh.getRange(row,1,1,headers.length).getValues()[0];sh.getRange(row,1,1,headers.length).setValues([headers.map(function(h,i){return Object.prototype.hasOwnProperty.call(obj,h)?safeCell_(obj[h]):old[i];})]);}
function setupSystem(){var ss=spreadsheet_();Object.keys(SHEETS_).forEach(function(name){var sh=ss.getSheetByName(name)||ss.insertSheet(name);if(sh.getLastRow()===0)sh.getRange(1,1,1,SHEETS_[name].length).setValues([SHEETS_[name]]);var actual=sh.getRange(1,1,1,SHEETS_[name].length).getValues()[0].map(String);if(actual.join('|')!==SHEETS_[name].join('|'))throw new Error('ส่วนหัวชีต '+name+' ไม่ตรงกับระบบ');sh.setFrozenRows(1);sh.getRange(1,1,1,SHEETS_[name].length).setFontWeight('bold').setBackground('#173f5f').setFontColor('#fff');});if(sheet_('SETTINGS').getLastRow()===1)sheet_('SETTINGS').getRange(2,1,5,3).setValues([['JOURNAL_NAME_TH','วารสารวิชาการและนวัตกรรมเซนต์เทเรซา','ชื่อวารสาร'],['CONTACT_EMAIL',properties_().getProperty('EDITORIAL_EMAIL')||'','อีเมลติดต่อ'],['TEMPLATE_URL','','ลิงก์แม่แบบ'],['GUIDELINES_URL','','ลิงก์หลักเกณฑ์'],['MAX_FILE_MB','15','ขนาดไฟล์สูงสุด']]);return 'ตั้งค่าฐานข้อมูลเรียบร้อย';}
function configureSystem_(spreadsheetId,rootFolderId,email){properties_().setProperties({SPREADSHEET_ID:String(spreadsheetId).trim(),ROOT_FOLDER_ID:String(rootFolderId).trim(),EDITORIAL_EMAIL:String(email||'').trim()});return setupSystem();}
function digest_(value){return Utilities.computeDigest(Utilities.DigestAlgorithm.SHA_256,value,Utilities.Charset.UTF_8).map(function(b){return ('0'+(((b+256)%256).toString(16))).slice(-2);}).join('');}
function setEditorialPassword_(password){if(!password||String(password).length<6)throw userError_('รหัสผ่านต้องมีอย่างน้อย 6 ตัวอักษร');properties_().setProperty('ADMIN_PASSWORD_HASH',digest_(String(password)));return 'ตั้งรหัสผ่านเรียบร้อย';}
function setting_(key,fallback){var row=rows_('SETTINGS').find(function(r){return String(r.key)===key;});return row&&row.value!==''?row.value:fallback;}
function getPublicConfig(){return response_(function(){return {journalName:setting_('JOURNAL_NAME_TH','วารสารวิชาการและนวัตกรรมเซนต์เทเรซา'),statuses:STJ_STATUSES_,templateUrl:setting_('TEMPLATE_URL',''),guidelinesUrl:setting_('GUIDELINES_URL','')};});}
function nextId_(){var year=buddhistYear_(new Date()),prefix='STJ-'+year+'-',max=rows_('SUBMISSIONS').map(function(r){return String(r.manuscript_id);}).filter(function(id){return id.indexOf(prefix)===0;}).map(function(id){return Number(id.slice(prefix.length));}).reduce(function(m,n){return Math.max(m,n||0);},0);return formatManuscriptId_(year,max+1);}
function childFolder_(parent,name){var found=parent.getFoldersByName(name);return found.hasNext()?found.next():parent.createFolder(name);}
function folders_(id){var root=DriveApp.getFolderById(requiredProperty_('ROOT_FOLDER_ID')),manuscript=childFolder_(childFolder_(root,id.split('-')[1]),id),result={root:manuscript};['01_Submission','02_Review','03_Revision','04_Accepted','05_Published'].forEach(function(name){result[name]=childFolder_(manuscript,name);});return result;}
function saveFile_(folder,blob,id,category,required,allowed){if(!blob||typeof blob.getBytes!=='function'||blob.getBytes().length===0){if(required)throw userError_('กรุณาแนบไฟล์ '+category);return'';}if(blob.getBytes().length>15*1024*1024)throw userError_('ไฟล์ '+category+' มีขนาดเกิน 15 MB');var name=clean_(blob.getName(),180),ext=(name.split('.').pop()||'').toLowerCase();if(allowed.indexOf(ext)<0)throw userError_('ชนิดไฟล์ '+category+' ไม่ถูกต้อง');blob.setName(id+'_'+category+'.'+ext);return folder.createFile(blob).getId();}
function parseForm_(form){var data={};Object.keys(form||{}).forEach(function(k){if(typeof form[k]!=='object')data[k]=form[k];});try{data.authors=JSON.parse(String(form.authors_json||'[]'));}catch(e){throw userError_('ข้อมูลผู้เขียนไม่ถูกต้อง');}return data;}
function submitManuscript(form){return response_(function(){var ownerId=requireAuthor_(form.author_token);ensureAccounts_();var data=parseForm_(form),authors=validateSubmissionData_(data),lock=LockService.getScriptLock();lock.waitLock(30000);try{var id=nextId_(),created=new Date(),fs=folders_(id),target=fs['01_Submission'];var row={manuscript_id:id,submitted_at:created,title_th:clean_(data.title_th,500),title_en:clean_(data.title_en,500),article_type:clean_(data.article_type,40),department:clean_(data.department,250),keywords_th:clean_(data.keywords_th,500),keywords_en:clean_(data.keywords_en,500),abstract_th:clean_(data.abstract_th,10000),abstract_en:clean_(data.abstract_en,10000),work_origin:clean_(data.work_origin,100),previously_published:String(data.previously_published)==='true',previous_publication_details:clean_(data.previous_publication_details,2000),ai_used:String(data.ai_used)==='true',ai_tools:clean_(data.ai_tools,500),ai_purposes:clean_(data.ai_purposes,1000),ai_details:clean_(data.ai_details,3000),human_data_used:String(data.human_data_used)==='true',participant_groups:clean_(data.participant_groups,1000),ethics_document_status:clean_(data.ethics_document_status,50),status:'SUBMITTED',public_note:'',private_note:'',drive_folder_id:fs.root.getId(),word_file_id:saveFile_(target,form.word_file,id,'manuscript_word',true,['docx']),pdf_file_id:saveFile_(target,form.pdf_file,id,'manuscript_pdf',true,['pdf']),certificate_file_id:saveFile_(target,form.certificate_file,id,'author_certificate',false,['pdf','doc','docx']),ai_disclosure_file_id:saveFile_(target,form.ai_disclosure_file,id,'ai_disclosure',false,['pdf','doc','docx']),ethics_file_id:saveFile_(target,form.ethics_file,id,'ethics',false,['pdf','doc','docx']),updated_at:created};append_('SUBMISSIONS',row);sheet_('USER_SUBMISSIONS').appendRow([ownerId,id]);authors.forEach(function(a,i){append_('AUTHORS',{manuscript_id:id,author_order:i+1,is_corresponding:i===0,name_th:clean_(a.name_th,250),name_en:clean_(a.name_en,250),role:clean_(a.role,30),department:clean_(a.department,250),email:normalizeEmail_(a.email),phone:clean_(a.phone,50),grade_level:clean_(a.grade_level,50),classroom:clean_(a.classroom,50),advisor_name:clean_(a.advisor_name,250),advisor_department:clean_(a.advisor_department,250)});});append_('STATUS_LOG',{manuscript_id:id,changed_at:created,from_status:'',to_status:'SUBMITTED',public_note:'ระบบได้รับบทความแล้ว',private_note:'',actor:'AUTHOR'});var warning='';try{if(MailApp.getRemainingDailyQuota()<1)throw new Error('quota');MailApp.sendEmail({to:normalizeEmail_(authors[0].email),subject:'ยืนยันการรับบทความ '+id,htmlBody:'<p>ระบบได้รับบทความ <b>'+escapeHtml_(row.title_th)+'</b> แล้ว</p><p>รหัสบทความ: <b>'+id+'</b></p>'});}catch(e){warning='บันทึกบทความแล้ว แต่ส่งอีเมลยืนยันไม่สำเร็จ';}return {manuscriptId:id,title:row.title_th,statusLabel:STJ_STATUSES_.SUBMITTED,emailWarning:warning};}finally{lock.releaseLock();}});}
function trackManuscript(query){return response_(function(){var id=normalizeId_(query&&query.manuscriptId),email=normalizeEmail_(query&&query.email),submission=rows_('SUBMISSIONS').find(function(r){return normalizeId_(r.manuscript_id)===id;}),author=rows_('AUTHORS').find(function(r){return normalizeId_(r.manuscript_id)===id&&String(r.is_corresponding).toLowerCase()==='true'&&normalizeEmail_(r.email)===email;});if(!submission||!author)throw userError_('ไม่พบข้อมูลที่ตรงกับรหัสบทความและอีเมล');return publicTrackingView_(submission,rows_('STATUS_LOG').filter(function(r){return normalizeId_(r.manuscript_id)===id;}));});}
function editorLogin(credentials){return response_(function(){var actual=digest_(String(credentials&&credentials.password||'')),expected=properties_().getProperty('ADMIN_PASSWORD_HASH');if(!expected)throw userError_('ยังไม่ได้ตั้งรหัสผ่านกลางของกองบรรณาธิการ');if(actual!==expected){Utilities.sleep(350);throw userError_('รหัสผ่านไม่ถูกต้อง');}var token=Utilities.getUuid().replace(/-/g,'')+Utilities.getUuid().replace(/-/g,'');CacheService.getScriptCache().put('session:'+digest_(token),'1',7200);return {token:token,expiresIn:7200};});}
function requireEditor_(token){if(!token||!CacheService.getScriptCache().get('session:'+digest_(String(token))))throw userError_('เซสชันหมดอายุ กรุณาเข้าสู่ระบบใหม่');}
function editorLogout(token){return response_(function(){if(token)CacheService.getScriptCache().remove('session:'+digest_(String(token)));return true;});}
function getDashboard(request){return response_(function(){requireEditor_(request&&request.token);var q=clean_(request.query,200).toLowerCase(),status=clean_(request.status,30),type=clean_(request.type,40),authors={};rows_('AUTHORS').filter(function(a){return String(a.is_corresponding).toLowerCase()==='true';}).forEach(function(a){authors[a.manuscript_id]=a;});var all=rows_('SUBMISSIONS'),counts={ALL:all.length};Object.keys(STJ_STATUSES_).forEach(function(s){counts[s]=all.filter(function(r){return String(r.status)===s;}).length;});var list=all.filter(function(r){return(!status||r.status===status)&&(!type||r.article_type===type)&&(!q||[r.manuscript_id,r.title_th,r.title_en,authors[r.manuscript_id]&&authors[r.manuscript_id].name_th].join(' ').toLowerCase().indexOf(q)>=0);}).slice(-300).reverse().map(function(r){return {manuscriptId:r.manuscript_id,title:r.title_th,author:authors[r.manuscript_id]?authors[r.manuscript_id].name_th:'',type:r.article_type,status:r.status,statusLabel:STJ_STATUSES_[r.status]||r.status};});return {counts:counts,mailQuota:MailApp.getRemainingDailyQuota(),rows:list};});}
function getSubmissionDetail(request){return response_(function(){requireEditor_(request&&request.token);var id=normalizeId_(request.manuscriptId),s=rows_('SUBMISSIONS').find(function(r){return normalizeId_(r.manuscript_id)===id;});if(!s)throw userError_('ไม่พบบทความ');return {submission:s,authors:rows_('AUTHORS').filter(function(a){return normalizeId_(a.manuscript_id)===id;}),timeline:rows_('STATUS_LOG').filter(function(r){return normalizeId_(r.manuscript_id)===id;}),statuses:STJ_STATUSES_};});}
function updateSubmissionStatus(request){return response_(function(){requireEditor_(request&&request.token);var id=normalizeId_(request.manuscriptId),status=clean_(request.status,30);if(!STJ_STATUSES_[status])throw userError_('สถานะไม่ถูกต้อง');var s=rows_('SUBMISSIONS').find(function(r){return normalizeId_(r.manuscript_id)===id;});if(!s)throw userError_('ไม่พบบทความ');var now=new Date(),pub=clean_(request.publicNote,2000),priv=clean_(request.privateNote,3000);update_('SUBMISSIONS',s._row,{status:status,public_note:pub,private_note:priv,updated_at:now});append_('STATUS_LOG',{manuscript_id:id,changed_at:now,from_status:s.status,to_status:status,public_note:pub,private_note:priv,actor:'EDITOR'});return {manuscriptId:id,status:status,statusLabel:STJ_STATUSES_[status]};});}
function escapeHtml_(value){return String(value==null?'':value).replace(/[&<>"']/g,function(c){return {'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c];});}


