function jReminderDateKey_(value){return Object.prototype.toString.call(value)==='[object Date]'?Utilities.formatDate(value,'Asia/Bangkok','yyyy-MM-dd'):String(value||'').slice(0,10);}
function jPortal_(){return 'https://theerawa21.github.io/STJ-Manuscript-Submission-System/reviewer.html';}
function jQueue_(to,template,id,subject,message,key){if(!to)return;if(jRows_('NOTIFICATIONS').some(function(r){return r.dedupe_key===key;}))return;jAppend_('NOTIFICATIONS',{notification_id:jUuid_(),recipient:normalizeEmail_(to),template:template,manuscript_id:id,subject:clean_(subject,200),body:clean_(message,40000),dedupe_key:key,status:'Pending',attempts:0});}
function jAuthorMail_(s,template,message,key){var a=rows_('AUTHORS').find(function(a){return a.manuscript_id===s.manuscript_id&&String(a.is_corresponding)==='true';});if(a)jQueue_(a.email,template,s.manuscript_id,template+' '+s.manuscript_id,s.title_th+'\nสถานะ: '+(journalStates_()[s.status]||s.status)+'\n'+message+'\nเปิดระบบ: https://theerawa21.github.io/STJ-Manuscript-Submission-System/system.html#account',key);}
function jEditorMail_(s,template,message,key){jQueue_(properties_().getProperty('EDITORIAL_EMAIL'),template,s.manuscript_id,template+' '+s.manuscript_id,s.title_th+'\n'+message+'\nเปิดระบบ: https://theerawa21.github.io/STJ-Manuscript-Submission-System/system.html#editor',key);}
function processJournalJobs_(){
  if(properties_().getProperty('JOURNAL_READY')!=='true')return;var lock=LockService.getScriptLock();if(!lock.tryLock(1000))return;
  try{
    var today=Utilities.formatDate(new Date(),'Asia/Bangkok','yyyy-MM-dd');
    jRows_('REVIEW_ASSIGNMENTS').filter(function(a){return !a.cancelled_at&&a.review_status!=='Completed'&&a.invitation_status==='Accepted';}).forEach(function(a){var due=Utilities.formatDate(new Date(a.due_at),'Asia/Bangkok','yyyy-MM-dd'),days=Math.round((new Date(due).getTime()-new Date(today).getTime())/86400000),kind=days===3?'Review Due Soon':days===0?'Review Reminder':days<0?'Review Overdue':'';if(!kind)return;var previous=jRows_('REMINDER_LOG').filter(function(r){return r.assignment_id===a.assignment_id&&jReminderDateKey_(r.due_date)===due&&r.reminder_type===kind;});if(previous.some(function(r){return days>=0||Date.now()-new Date(r.sent_at||r.queued_at).getTime()<7*86400000;}))return;var reviewer=rows_('REVIEWERS').find(function(r){return r.reviewer_id===a.reviewer_id&&String(r.active)==='true';});if(!reviewer)return;var key='reminder:'+a.assignment_id+':'+kind+':'+due+':'+(days<0?today:'once');jQueue_(reviewer.email,kind,a.manuscript_id,'แจ้งเตือนงานประเมิน '+a.manuscript_id,'ครบกำหนด '+due+'\nขอลิงก์เข้าสู่ระบบ: '+jPortal_(),key);jAppend_('REMINDER_LOG',{assignment_id:a.assignment_id,reminder_type:kind,due_date:due,queued_at:jNow_()});});
    var pending=jRows_('NOTIFICATIONS').filter(function(n){return n.status==='Pending'&&(!n.next_attempt_at||new Date(n.next_attempt_at).getTime()<=Date.now());}).slice(0,20);
    pending.forEach(function(n){if(MailApp.getRemainingDailyQuota()<1)return;try{var message=n.body;if(message.indexOf('{{TOKEN}}')>=0){var r=rows_('REVIEWERS').find(function(r){return r.email===n.recipient&&String(r.active)==='true';}),assignment=n.template==='Reviewer Invitation'?n.dedupe_key.slice(7):'';if(!r||assignment&&(!jFind_('REVIEW_ASSIGNMENTS','assignment_id',assignment)||jFind_('REVIEW_ASSIGNMENTS','assignment_id',assignment).cancelled_at))throw userError_('คำเชิญไม่พร้อมใช้งาน');message=message.replace('{{TOKEN}}',jToken_(r.reviewer_id,assignment,assignment?'INVITATION':'LOGIN'));}
      MailApp.sendEmail({to:n.recipient,subject:'วารสารเซนต์เทเรซา — '+n.subject,body:'วารสารวิชาการและนวัตกรรมเซนต์เทเรซา\nSaint Theresa Journal of Academic Studies and Innovation\nรหัสบทความ: '+(n.manuscript_id||'-')+'\n'+message});jUpdate_('NOTIFICATIONS',n._row,{status:'Sent',sent_at:jNow_(),attempts:Number(n.attempts)+1,safe_error:''});if(n.dedupe_key.indexOf('reminder:')===0){var parts=n.dedupe_key.split(':');jRows_('REMINDER_LOG').filter(function(r){return r.assignment_id===parts[1]&&r.reminder_type===parts[2]&&jReminderDateKey_(r.due_date)===parts[3]&&!r.sent_at;}).forEach(function(r){jUpdate_('REMINDER_LOG',r._row,{sent_at:jNow_()});});}
    }catch(e){var attempts=Number(n.attempts)+1;jUpdate_('NOTIFICATIONS',n._row,{attempts:attempts,status:attempts>=5?'Failed':'Pending',next_attempt_at:new Date(Date.now()+Math.pow(2,attempts)*3600000).toISOString(),safe_error:'ส่งอีเมลไม่สำเร็จ กรุณาตรวจโควตาและข้อมูลผู้รับ'});}});
  }finally{lock.releaseLock();}
}
function flushJournalNotifications(q){return response_(function(){requireEditor_(q.token);jReady_();processJournalJobs_();return {message:'ประมวลผลคิวแล้ว กรุณาตรวจประวัติการแจ้งเตือน'};});}


// Run once from the project editor to grant the trigger-management scope.
// This reads trigger metadata and does not dispatch messages or create a trigger.
function authorizeJournalAutomation(){return ScriptApp.getProjectTriggers().length;}
